b2wdigital/restQL-clojure

- src/clj/restql/core/api/restql.clj
- src/clj/restql/core/transformations/aggregation.clj
- src/resources/grammar.ebnf
- test/clj/restql/core/api/restql_test.clj
- test/clj/restql/core/transformations/aggregation_test.clj
This PR addresses:
* Simple Aggregation
* List Aggregation
The Complex Aggregation use case is currently not supported.
It requires a major refactoring in the Parser code.
> Response aggregation (#5)

- src/main/restql/core/response-util.clj
WIP solution to [restQL-server issue 15](https://github.com/B2W-BIT/restQL-server/issues/15)
> feat(cache-control) Finding the minimal max-age value among headers

- src/main/restql/core/response/headers.clj
- test/unit/restql/core/response/headers_test.clj
Fixing issue if no cache-control parameters were found
> fix(http-header) covering no cache-control parameters scenario

- src/main/restql/core/async_runner.clj
- test/integration/restql/sni_test.clj
> fix(log/warn) verifying if result is a list before throwing the warning

- src/main/restql/core/api/response_builder.clj
- src/main/restql/core/async_request.clj
- src/main/restql/core/request.clj
- src/main/restql/core/statement.clj
- test/integration/restql/restql_test.clj
- test/unit/restql/core/request_test.clj
- test/unit/restql/core/statement_test.clj
Closes B2W-BIT/restQL-http/issues/50
> Fix wrong multiplex when service returns an array

- src/main/restql/parser/core.clj
- test/integration/restql/restql_test.clj
Closing B2W-BIT/restQL-http/issues/57
> fix(parser) closing issue for params values with quotes generates exception

- src/main/restql/core/async_request.clj
- src/main/restql/core/statement.clj
- test/integration/restql/restql_test.clj
- test/unit/restql/core/statement_test.clj
This PR fixes: 
- Non multiplex calls response;
- Multiplex calls response;
- Response with lists.
> fix(response): multiplex calls

- src/main/restql/parser/producer.clj
- src/resources/grammar.ebnf
- test/integration/restql/restql_test.clj
Closing issues B2W-BIT/restQL-clojure/issues/23 and B2W-BIT/restQL-http/issues/60
> feat(parser) allow directly using variables in 'with' statement

- src/main/restql/core/statement.clj
- src/main/restql/core/util/get_in_with_list_support.clj
- test/integration/restql/restql_test.clj
- test/unit/restql/core/statement_test.clj
Closes [B2W-BIT/restQL-http#64]
> Fix: chained queries with lists and maps combined

- src/main/restql/core/async_request.clj
- src/main/restql/core/request.clj
- src/main/restql/core/url.clj
- src/main/restql/parser/producer.clj
- src/resources/grammar.ebnf
- test/integration/restql/request_post_test.clj
- test/integration/restql/restql_test.clj
- test/unit/restql/core/request_test.clj
- test/unit/restql/core/url_test.clj
- test/unit/restql/parser/core_test.clj
Closes B2W-BIT/restQL-http/issues/51
> feat(request): change post to use with rule as body of request 

- src/main/restql/core/encoders/core.clj
- test/integration/restql/restql_test.clj
- test/unit/restql/core/statement_test.clj
Closes B2W-BIT/restQL-http/issues/70
> fix(encoders): add vector as case to be stringifyed

- src/main/restql/core/statement.clj
- src/main/restql/core/transformations/aggregation.clj
- src/main/restql/core/validator/core.clj
- src/main/restql/parser/core.clj
- src/main/restql/parser/producer.clj
- src/resources/grammar.ebnf
- test/integration/restql/restql_test.clj
- test/unit/restql/core/transformations/aggregation_test.clj
Closes [B2W-BIT/restQL-http/issues/31]
> Feat(aggregation): add in operator [B2W-BIT/restQL-http#31]

- src/main/restql/core/async_request.clj
Closes B2W-BIT/restQL-http/issues/63.
> Chore(log): log underlying request erros as warn

- src/main/restql/core/request.clj
- test/integration/restql/restql_test.clj
Closes B2W-BIT/restQL-http/issues/79
> Add :metadata to response

- src/main/restql/core/transformations/select.clj
- test/integration/restql/filter_test.clj
Closes [B2W-BIT/restQL-http/issues/81]
> feat(filter): change select to works with nested list

- src/main/restql/core/api/response_builder.clj
- src/main/restql/core/api/restql.clj
- src/main/restql/core/runner/request.clj
- test/integration/restql/restql_test.clj
- test/integration/restql/test_util.clj
Solution to B2W-BIT/restQL-http/issues/89 and to B2W-BIT/restQL-http/issues/90
>  fix(headers): substitute request headers with any matching query headers  and show headers in debug

- src/main/restql/core/runner/request.clj
- test/integration/restql/restql_test.clj
> fix(headers): transform header value from 'nil' to empty string

- src/main/restql/core/runner/executor.cljc
- src/main/restql/core/runner/request.clj
- src/main/restql/core/runner/request.cljs
- src/main/restql/core/statement/resolve_chained_values.cljc
- src/main/restql/parser/producer.cljc
- test/integration/restql/restql_test.clj
- test/unit/restql/core/statement/resolve_chained_values_test.clj
This PR breaks contract! v3 !!!
> feat(request): skip request if a parameter is not present

- src/main/restql/core/api/restql.cljc
- test/integration/restql/restql_test.clj
- test/integration/restql/timeout_test.clj
- test/unit/restql/parser/core_test.clj
Closes B2W-BIT/restQL-http/issues/143
> fix(core): use timeout from query [B2W-BIT/restQL-http/issues/143]

- src/main/restql/core/api/restql.cljc
- test/integration/restql/restql_test.clj
> fix(restQL-api): return exception-ch value if exist

- src/main/restql/core/transformations/select.cljc
- test/unit/restql/core/transformations/select_test.clj
Closes B2W-BIT/restQL-http/issues/164
> fix(select): adjust selects for not equals list sizes

- src/main/restql/core/statement/apply_encoders.cljc
- test/unit/restql/core/statement/apply_encoders_test.clj
- test/unit/restql/parser/core_test.clj
Closes [B2W-BIT/restQL-http/issues/170]
> fix(statement): dont encode body params by default

- src/resources/grammar.ebnf
- test/integration/restql/restql_test.clj
- test/unit/restql/parser/query_test.clj
Closes [B2W-BIT/restQL-http/issues/173]
> feat(grammar): allow brackets on url parameters(#173)

- project.clj
- src/main/restql/core/statement/resolve_chained_values.cljc
- test/integration/restql/chained_test.clj
- test/integration/restql/test_util.clj
Now, if we don't find the chained value in the response body, we will try to find it in the headers.
> feat(chained): get chained from headers if not in the body
